# Generated by Django 5.1.6 on 2025-02-22 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('user', 'book')},
        ),
    ]
